# -*- coding: utf-8 -*-
"""SalesForecasting-MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1Kj_J2jUYaPziRw55wgV_eWw7XLuMQt
"""

!pip install -Uq upgini catboost

from os.path import exists
import pandas as pd

df_path = "https://github.com/upgini/upgini/raw/main/notebooks/train.csv.zip"
df = pd.read_csv(df_path)
df = df.sample(n=10000 , random_state=0)
df["store"] = df["store"].astype(str) # conv to str as we want the numbered column to be perceived like it has categories, not continuous vals to perform operations on
df["item"] = df["item"].astype(str)

df["date"] = pd.to_datetime(df["date"]) # interpret as date, not standard text

df.sort_values("date", inplace = True)
df.reset_index(inplace = True, drop = True) # discard the old index (that is now random) and replace it w a new sequenced one
df.head()

train = df[df["date"] < "2017-01-01"]
test = df[df["date"] >= "2017-01-01"]

train_features = train.drop(columns=["sales"])
train_target = train["sales"]
test_features = test.drop(columns=["sales"])
test_target = test["sales"]

from upgini import FeaturesEnricher, SearchKey
from upgini.metadata import CVType


enricher = FeaturesEnricher(
    search_keys = {
        "date": SearchKey.DATE,
    },
    CV = CVType.time_series
)

enricher.fit(train_features,
             train_target,
             eval_set=[(test_features, test_target)])

from catboost import CatBoostRegressor
from catboost.utils import eval_metric

model = CatBoostRegressor(verbose=False, allow_writing_files=False, random_state=0)

enricher.calculate_metrics(
    train_features, train_target,
    eval_set = [(test_features, test_target)],
    estimator = model,
    scoring = "mean_absolute_percentage_error"
)

enriched_train_features = enricher.transform(train_features, keep_input = True)
enriched_test_features = enricher.transform(test_features, keep_input = True)

if enriched_train_features is not None:
    enriched_train_features.head()
else:
    print("Warning: enriched_train_features is None, likely due to upgini user limits.")
    print("Please check the output of the previous cell for 'Unregistered-user limit' messages.")

model.fit(train_features, train_target)
preds = model.predict(test_features)
eval_metric(test_target.values, preds, "SMAPE")

model.fit(enriched_train_features, train_target)
enriched_preds = model.predict(enriched_test_features)
eval_metric(test_target.values, enriched_preds, "SMAPE")

set(enriched_train_features.columns) == set(enriched_test_features.columns)